app/posts/models.py
from datetime import datetime

from app import db


class Posts(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(50))
    text = db.Column(db.String(150))
    data_create = db.Column(db.DateTime, default=datetime.now)

app/forms.py
from wtforms import Form, StringField


class Posts_Form(Form):
    title = StringField('Title')
    text = StringField('Text')


class Vlasnik(Form):
    name = StringField('Name')
    age = StringField('Age')
    city = StringField('City')


class Pet(Form):
    name_pet = StringField('Name_pet')
    age_pet = StringField('Age_pet')
    typ_pet = StringField('Type_pet')

app/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy

from config import DevConf

app = Flask(__name__)
# app.config['DEBUG'] = True  # 1
# app.config.update(DEBUG=True)  # 2
# app.config.from_json('..\config.json') # 3
app.config.from_object(DevConf)

db = SQLAlchemy(app)
from .posts.views import posts
app.register_blueprint(posts, url_prefix='/posts')

from app import views

app/posts/views.py
from flask import Blueprint, render_template, request

from app import db
from app.forms import Pet, Posts_Form

posts = Blueprint('posts', __name__, template_folder='templates', static_folder='static')
from .models import Posts


@posts.route('/')
def index():
    return render_template('posts/index.html')


@posts.route('/new/', methods=['POST', 'GET'])
def new_posts():
    # db.create_all()
    form = Posts_Form()
    title = ''
    text = ''
    if request.method == 'POST':
        title = request.form['title']
        text = request.form['text']
        post = Posts(title=title, text=text)
        db.session.add(post)
        db.session.commit()
    return render_template('posts/new_posts.html', title=title, text=text, form=form)


@posts.route('/all')
def all_posts():
    post = Posts.query.all()
    return render_template('posts/all.html', post=post)



# @posts.route('/new/', methods=['POST', 'GET'])
# def new_posts():
#     form = Vlasnik()
#     name = ''
#     age = ''
#     city = ''
#     if request.method == 'POST':
#         name = request.form['name']
#         age = request.form['age']
#         city = request.form['city']
#     clients_list.append({'id': len(clients_list) + 1, 'name': name, 'age': age, 'city': city, 'pets': []})
#     return render_template('posts/new_posts.html', name=name, age=age, city=city, form=form)


@posts.route('/new/pet', methods=['POST', 'GET'])
def pet_posts():
    form_pet = Pet()
    name_pet = ''
    age_pet = ''
    typ_pet = ''
    if request.method == 'POST':
        name_pet = request.form['name_pet']
        age_pet = request.form['age_pet']
        typ_pet = request.form['typ_pet']
    return render_template('posts/pet_posts.html', name_pet=name_pet, age_pet=age_pet, typ_pet=typ_pet,
                           form_pet=form_pet, )

# @posts.route('/typ/cet')
# def cet():
#     dik = pet_posts.dik
#     return render_template('posts/cet.html', dik=dik )

app/views.py
from flask import render_template, request

from app import app
from posts import posts
from some import User, dikts
from users import users

for user in users:
    user['posts'] = []
    for post in posts:
        if user['id'] == post['userId']:
            user['posts'].append(post)


@app.route('/')
def hello_dev():
    return render_template('hello.html')


@app.route('/age')
def ages():
    user = User
    d = dikts
    return render_template('age.html', user=user, d=d)


@app.route('/mail')
def mails():
    user1 = User
    us = users
    return render_template('mail.html', user=user1, us=us)


@app.route('/<ids>')
def id_user(ids):
    us = users
    return render_template('id_user.html', us=us, ids=int(ids))


@app.route('/city/<city>')
def users_by_city(city):
    return render_template('id_user.html', users=list(filter(lambda item: item['address']['city'] == city, users)))


@app.route('/search/', methods=['POST', 'GET'])
def search():
    result = ''
    if request.method == 'POST':
        result = request.form['search']
    return render_template('search.html', search=result)

app/templates/age.html
{% extends 'hello.html' %}
{% block title %}
 Age
{% endblock %}
{#{%  block title_content %}#}
{#  Home#}
{#{% endblock %}#}
{% block content %}
        <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href={{ url_for('static', filename = 'style.css') }} rel="stylesheet" >
</head>
<body>
    <h1>My age => {{ user.age }}</h1>
    {% for k,v in d.items() %}
        <div>
        k = {{ k }}
        v = {{ v }}
        </div>
    {% endfor %}

    <h2><a href="/">=<</a></h2>
</body>
</html>
{% endblock %}

app/templates/hello.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} {% endblock %} | My app</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link href={{ url_for('static', filename = 'css/style.css') }} rel="stylesheet" >
    {% block ccs_js_img %}{% endblock %}
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light, navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{{ url_for('hello_dev') }}">Home <span class="sr-only">(current)</span></a>
      </li>
        <li class="nav-item active">
        <a class="nav-link" href="{{ url_for('ages') }}">Age <span class="sr-only">(current)</span></a>
      </li>
        <li class="nav-item active">
        <a class="nav-link" href="{{ url_for('mails') }}">Mail <span class="sr-only">(current)</span></a>
      </li>
        <li class="nav-item active">
        <a class="nav-link" href="{{ url_for('posts.index') }}">Posts <span class="sr-only">(current)</span></a>
      </li>
        <li class="nav-item active">
         <a class="nav-link" href="{{ url_for('posts.new_posts') }}">New Posts <span class="sr-only">(current)</span></a>
      </li>
        <li class="nav-item active">
         <a class="nav-link" href="{{ url_for('posts.pet_posts') }}">New Pet <span class="sr-only">(current)</span></a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0" action="{{ url_for('search') }}" method="POST">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="search" value="{{ request.args.get('search', '') }}">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>
<div class="container">
    <div>It is my site</div>
    <div>
        {% block title_content %} {% endblock %}
        <div>{% block content %} {%  endblock %}</div>
    </div>
</div>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>

<footer class="page-footer font-small special-color-dark pt-4">
<div class="card text-center">

  <div class="card-body">
    <h5 class="card-title">Special title treatment</h5>
    <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
    <a href="#" class="btn btn-primary">Go somewhere</a>
  </div>
  <div class="card-footer text-muted">
    2 days ago
  </div>
</div>


</footer>
<!-- Footer -->
</body>
</html>

app/templates/id_user.html
{% extends 'hello.html' %}
{% block title %}
 User
{% endblock %}
{% block content %}

        <div>
           <h1> User id == {{ ids }}</h1>
                {% for i in us %}
                   {% if i.id == ids %}
                      <h1>Name => {{ i.name }}<br>
                         Username => {{ i.username }}<br>
                      Email => {{ i.email }}
                      </h1>
                    {% endif %}
                {% endfor %}
        </div>

<div class="item">
    {% for i in users %}
        <div class="users">
        <div>User id => {{ i.id }}</div>
        <div>Name => {{ i.name }}</div>
        <div>Username => {{ i.username }}</div>
        <div>address => {{ i.address['city'] }}</div>
        </div>
        <div class="posts">
                 {% for posts in i['posts'] %}
                    <div>userId =>{{ posts.userId }}</div>
                    <div>title => {{ posts.title }}</div>
                    <div></div>
                {% endfor %}
        </div>
    {% endfor %}
</div>

{% endblock %}

app/templates/mail.html
{% extends 'hello.html' %}
{% block title %}
 Mail
{% endblock %}
{#{%  block title_content %}#}
{#  Home#}
{#{% endblock %}#}
{% block content %}
        <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link href={{ url_for('static', filename = 'style.css') }} rel="stylesheet" >
</head>
<body>
  <h1>My mail => {{ user.mail }}</h1>
  <div class="card" style="width: 18rem;">
  <img src="https://i.pinimg.com/736x/98/2b/01/982b012530231e444573cc35bdeed3cd.jpg" class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title">Card title</h5>
    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
    <a href="/" class="btn btn-primary">Go somewhere</a>
  </div>
</div>
<div class="item">
    {% for i in us %}
        <div class="users">
        <div>User id => {{ i.id }}</div>
        <div>Name => {{ i.name }}</div>
        <div>Username => {{ i.username }}</div>
        </div>
        <div class="posts">
                 {% for posts in i['posts'] %}
                    <div>userId =>{{ posts.userId }}</div>
                    <div>title => {{ posts.title }}</div>
                    <div></div>
                {% endfor %}
        </div>
    {% endfor %}
</div>

<h2><a href="/">=<</a></h2>
</body>
</html>
{% endblock %}

app/templates/search.html
{% extends 'hello.html' %}

{% block ccs_js_img %}

{% endblock %}

{% block title %}
 Posts | index
{% endblock %}

{% block content %}
search = {{ search }}

{% endblock %}